# Generated by Django 5.0.4 on 2024-04-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_profile_pictur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pictur',
        ),
    ]
