# Generated by Django 5.0.4 on 2024-04-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
